name: Publicar Documentación

on:
  push:
    branches:
      - main  # Cambia a 'master' si tu rama principal se llama así

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Asegúrate de que esta versión coincida con tu proyecto

      - name: Instalar DocFX
        run: |
          sudo apt-get install unzip -y
          curl -L -o docfx.zip https://github.com/dotnet/docfx/releases/download/v2.78.3/docfx.zip
          unzip docfx.zip -d docfx
          sudo mv docfx/docfx /usr/local/bin/docfx

      - name: Generar documentación
        run: |
          cd docfx_project
          docfx build

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docfx_project/_site
