name: Publicar Documentación

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Compilar proyecto con XML Docs
        run: dotnet build --configuration Release

      - name: Instalar DocFX
        run: |
          dotnet tool install --global docfx
          echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Generar documentación
        run: |
          cd docfx_project
          docfx build

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docfx_project/_site
