name: Publicar Documentación

on:
  push:
    branches:
      - main  # Cambia si tu rama principal es 'master' u otra

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Compilar solución con XML Docs habilitados
        run: dotnet build ./MyMath/MyMath.sln --configuration Release

      - name: Instalar DocFX globalmente
        run: |
          dotnet tool install --global docfx
          echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Generar documentación con DocFX
        run: |
          cd docfx_project
          docfx build

      - name: Publicar documentación en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docfx_project/_site
          publish_branch: gh-pages   # Opcional: define la rama donde se publicará la documentación
          keep_files: true  # Mantener archivos existentes para no sobrescribir el reporte de cobertura
