name: Release NuGet

on:
  push:
    tags:
      - 'v2022074258'  # Tag con tu código de matrícula

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Compilar y generar paquete NuGet
        run: dotnet pack MyMath/Math.Lib/Math.Lib.csproj --configuration Release -p:PackageVersion=2022074258

      - name: Publicar en GitHub Packages
        run: dotnet nuget push **/MyMath.*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Crear Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v2022074258
