name: Release NuGet Package

on:
  push:
    tags:
      - 'v*'   # Se activa al hacer push de un tag que comience con 'v'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Extract version number (remove leading 'v')
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore MyMath/MyMath.sln

      - name: Build project
        run: dotnet build MyMath/Math.Lib/Math.Lib.csproj -c Release

      - name: Pack NuGet package
        run: dotnet pack MyMath/Math.Lib/Math.Lib.csproj -c Release -o ./MyMath/nupkg /p:PackageVersion=$VERSION

      - name: Add GitHub Packages source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Publish package to GitHub Packages
        run: dotnet nuget push ./MyMath/nupkg/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
